name: multiple_identities
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_redux: ^0.5.0
  built_value: ^5.4.1
  built_collection: ^3.1.1
  rxdart: ^0.16.6
  redux_epics: ^0.9.0
  redux: ^3.0.0
  flutter_logger: any
  intl: any
  socket_io_client:
    git: https://github.com/long1eu/socket_io_client.git

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.1
  built_value_generator: ^5.4.1

flutter:
  uses-material-design: true

