name: multiple_identities
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  flutter_redux: any
  built_value: any
  built_collection: any
  rxdart: any
  redux_epics: any
  redux: any
  flutter_logger: any
  intl: any
  socket_io_client:
    git: https://github.com/long1eu/socket_io_client.git

dev_dependencies:
  build_runner: any
  built_value_generator: any

flutter:
  uses-material-design: true

